// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hash.sql

package database

import (
	"context"
)

const getHash = `-- name: GetHash :one
SELECT hashed_password
FROM users
WHERE email = $1
`

func (q *Queries) GetHash(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getHash, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
